version: '3'

services:
  smarthome-arduino-temperature:
    build: 
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
