version: '3'

networks:
  proxy:
    external: true
    name: proxynet

services:
  smarthome-arduino-temperature:
    restart: always
    env_file:
      - .env
    build: 
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smarthome-arduino-temperature.rule=Host(`${WEB_URL}`)"
      - "traefik.http.routers.smarthome-arduino-temperature.entrypoints=websecure"
      - "traefik.http.routers.smarthome-arduino-temperature.tls.certresolver=myresolver"
    networks:
      - proxy
