version: '3'

networks:
  proxy:
    external: true
    name: proxynet

services:
  site:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - 3001:3001
    networks:
      - proxy
